### ISSUE TITLE
Tries to re-upload same songs.

### ISSUE THREAD

**Issue by meganugen** [jaymoulin/google-music-manager#18]
I just uploaded my entire music collection. But then I see in the docker logs that it is still tries to upload the files but skips them with "ALREADY EXISTS" message. Have I messed up some flags or something for it to keep uploading my library in eternity? I masked my uploader ID below.

`sudo docker run -d --network host --name jaymoulin-googlemusicmanager --restart=unless-stopped -v /volume1/MyStuff/03-Musik:/media/library/upload -v /volume1/MyStuff/Downloads/GoogleMusic_download:/media/library/download -v /volume1/docker/jaymoulin-google-musicmanager/config:/root/oauth -e DOWNLOAD=false -e UPLOADER_ID=XX:XX:XX:XX:XX:XX jaymoulin/google-musicmanager`

**Comment by jaymoulin** [comment]
You may be interested in [Google MusicManager Deduplication API](https://github.com/jaymoulin/google-musicmanager-dedup-api). Cf https://github.com/jaymoulin/google-music-manager-uploader#deduplication-api

Also, I suggest you use `jaymoulin/google_music_uploader` image instead of manager since you pass the `DOWNLOAD=false` argument. Cf https://hub.docker.com/r/jaymoulin/google-music-uploader

If you like my products and you may want to support my work for maintaining and evolving them with donation on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).
